
#define COLOR_CYAN_NUMBER 1
#define COLOR_CYAN "\033[36m"

#define COLOR_RED_NUMBER 2
#define COLOR_RED "\033[31m" 

#define COLOR_GREEN_NUMBER 3
#define COLOR_GREEN "\033[32m" 

#define COLOR_YELLOW_NUMBER 4
#define COLOR_YELLOW "\033[33m" 

#define COLOR_MAGENTA_NUMBER 5
#define COLOR_MAGENTA "\033[35m" 

#define COLOR_BLUE_NUMBER 6
#define COLOR_BLUE "\033[34m" 

#define COLOR_WHITE_NUMBER 7
#define COLOR_WHITE "\033[37m"  

#define COLOR_RESET_NUMBER 8
#define COLOR_RESET "\033[0m"



#define COLOR_STATIC_OBJECT COLOR_CYAN
#define COLOR_STATIC_NUMBER COLOR_CYAN_NUMBER

#define COLOR_DYNAMIC_OBJECT COLOR_RED
#define COLOR_DYNAMIC_NUMBER COLOR_RED_NUMBER

#define COLOR_EMPTY_SPACE COLOR_WHITE
#define COLOR_EMPTY_NUMBER COLOR_WHITE_NUMBER