; Listing generated by Microsoft (R) Optimizing Compiler Version 19.36.32532.0 

include listing.inc

INCLUDELIB OLDNAMES

EXTRN	__imp___std_terminate:PROC
EXTRN	__security_check_cookie:PROC
EXTRN	__imp___CxxFrameHandler4:PROC
PUBLIC	??$max@H@std@@YAAEBHAEBH0@Z			; std::max<int>
PUBLIC	??$min@H@std@@YAAEBHAEBH0@Z			; std::min<int>
PUBLIC	?Draw_Square@Drawing2D@@SAXUObject2D@@0HPEAY1CI@CI@H@Z ; Drawing2D::Draw_Square
PUBLIC	?Draw_BresenhamLine@Drawing2D@@SAXUObject2D@@0HPEAY1CI@CI@H@Z ; Drawing2D::Draw_BresenhamLine
PUBLIC	__real@41cdcd6500000000
PUBLIC	__xmm@00000001000000010000000100000001
EXTRN	__std_terminate:PROC
EXTRN	__CxxFrameHandler4:PROC
EXTRN	__GSHandlerCheck:PROC
EXTRN	__GSHandlerCheck_EH4:PROC
EXTRN	__chkstk:PROC
EXTRN	memset:PROC
EXTRN	__security_cookie:QWORD
EXTRN	_fltused:DWORD
;	COMDAT pdata
pdata	SEGMENT
$pdata$?Draw_Square@Drawing2D@@SAXUObject2D@@0HPEAY1CI@CI@H@Z DD imagerel $LN29@Draw_Squar
	DD	imagerel $LN29@Draw_Squar+120
	DD	imagerel $unwind$?Draw_Square@Drawing2D@@SAXUObject2D@@0HPEAY1CI@CI@H@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?Draw_BresenhamLine@Drawing2D@@SAXUObject2D@@0HPEAY1CI@CI@H@Z DD imagerel $LN19@Draw_Brese
	DD	imagerel $LN19@Draw_Brese+231
	DD	imagerel $unwind$?Draw_BresenhamLine@Drawing2D@@SAXUObject2D@@0HPEAY1CI@CI@H@Z
;	COMDAT __xmm@00000001000000010000000100000001
CONST	SEGMENT
__xmm@00000001000000010000000100000001 DB 01H, 00H, 00H, 00H, 01H, 00H, 00H
	DB	00H, 01H, 00H, 00H, 00H, 01H, 00H, 00H, 00H
CONST	ENDS
;	COMDAT __real@41cdcd6500000000
CONST	SEGMENT
__real@41cdcd6500000000 DQ 041cdcd6500000000r	; 1e+09
CONST	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?Draw_BresenhamLine@Drawing2D@@SAXUObject2D@@0HPEAY1CI@CI@H@Z DQ 0000a541e000a1e01r ; 1.43637e-308
	DQ	0e01cf01e0009341er		; -9.69986e+154
	DQ	060157016c018d01ar		; 7.18586e+154
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?Draw_Square@Drawing2D@@SAXUObject2D@@0HPEAY1CI@CI@H@Z DQ 00001740500020501r ; 2.02093e-309
xdata	ENDS
END
