; Listing generated by Microsoft (R) Optimizing Compiler Version 19.36.32532.0 

include listing.inc

INCLUDELIB OLDNAMES

PUBLIC	?y_constructor@DynamicObject2D@@1HA		; DynamicObject2D::y_constructor
PUBLIC	?x_constructor@DynamicObject2D@@1HA		; DynamicObject2D::x_constructor
?y_constructor@DynamicObject2D@@1HA DD 01H DUP (?)	; DynamicObject2D::y_constructor
?x_constructor@DynamicObject2D@@1HA DD 01H DUP (?)	; DynamicObject2D::x_constructor
_BSS	ENDS
PUBLIC	?Set_StartingPoint@DynamicObject2D@@SAXHH@Z	; DynamicObject2D::Set_StartingPoint
END
